version: '3.1'

services:
  server:
    build: ./backend
    volumes:
     - ./backend/app:/app
    links:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    volumes:
     - ./frontend/app:/app
    links:
      - server
    ports:
      - "5001:5001"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: idp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-datavolume: