CREATE TABLE IF NOT EXISTS users (
	username VARCHAR(64) PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	password_hash VARCHAR(128) NOT NULL,
	organiser BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS events (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL UNIQUE,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,
	owner VARCHAR(20),
	FOREIGN KEY (owner) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS attendees (
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20),
	event_id INT,
	FOREIGN KEY (username) REFERENCES users(username),
	FOREIGN KEY (event_id) REFERENCES events(id)
);